# Generated by Django 5.2.4 on 2025-08-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("gym_owner", "Gym Owner"),
                    ("system_admin", "System Admin"),
                    ("staff", "Staff"),
                ],
                max_length=20,
            ),
        ),
    ]
