# Generated by Django 5.2.4 on 2025-08-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("info", "Info"),
                    ("warning", "Warning"),
                    ("error", "Error"),
                    ("success", "Success"),
                ],
                default="info",
                max_length=10,
            ),
        ),
    ]
